# Generated by Django 3.1.7 on 2021-04-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('disaster_name', models.FilePathField(path='/home/peyush/fy_project/xView2/xBD/')),
            ],
        ),
    ]
