# Generated by Django 3.1.7 on 2021-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BD_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_image', models.ImageField(max_length=50, upload_to='')),
                ('post_image', models.ImageField(max_length=50, upload_to='')),
                ('output_image', models.ImageField(blank=True, max_length=50, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectImage',
        ),
    ]
