# Generated by Django 3.1.7 on 2021-03-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('emp_image1', models.ImageField(upload_to='upload/')),
                ('name2', models.CharField(max_length=50)),
                ('emp_image2', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
