# Generated by Django 3.1.7 on 2021-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='output_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employee',
            name='percentage_change',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employee',
            name='select_model',
            field=models.CharField(choices=[('PcaKmeans', 'PCA K-means'), ('vgg19', 'VGG19')], default='PcaKmeans', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
