# Generated by Django 3.1.7 on 2021-03-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210316_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_image1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_image2',
            new_name='image2',
        ),
    ]
