# Generated by Django 3.2 on 2021-04-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BD_fixedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disasters', models.CharField(choices=[('gvol', 'guatemala-volcano'), ('ptsu', 'palu-tsunami'), ('harvey', 'hurricane-harvey'), ('srwf', 'santa-rosa-wildfire')], default='ptsu', max_length=30)),
            ],
        ),
    ]
