# Generated by Django 3.2 on 2021-04-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD_fixed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd_fixedmodel',
            name='path',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bd_fixedmodel',
            name='disasters',
            field=models.CharField(choices=[('gvol', 'guatemala-volcano'), ('ptsu', 'palu-tsunami'), ('harvey', 'hurricane-harvey'), ('srwf', 'santa-rosa-wildfire')], max_length=30),
        ),
    ]
