# Generated by Django 3.2 on 2021-04-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD_fixed', '0002_auto_20210421_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bd_fixedmodel',
            old_name='path',
            new_name='base_path',
        ),
    ]
