# Generated by Django 3.2 on 2021-04-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD_fixed', '0003_rename_path_bd_fixedmodel_base_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bd_fixedmodel',
            old_name='base_path',
            new_name='query',
        ),
    ]
